### ISSUE TITLE
if gauge.min == gauge.max, you get a NaN in the path data

### ISSUE THREAD

**Issue by BryanCrotaz** [Glavin001/ember-c3#106]
Suggest checking for this before passing down to c3 and adding 1 to gauge.max.

**Comment by maxwondercorn** [comment]
Internally the properties (data, gauge, bar, etc.) are bassically passed from the component attributes to the C3 generate function so there really isn't an easy way to verify the data.  

If there were only a few attributes it'd be pretty easy to put some guard logic in. They're hundreds (or more) of combinations on what attributes can be used and how data can be passed in. 

It would be difficult to catch all the issues and then maintain the addon.  I'd open an issue in the C3 repo and then we'd get the advantage when C3 is updated
