### ISSUE TITLE
Ember CLI Addon support

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/ember-c3#14]

**Comment by Robdel12** [comment]
Interesting. I'm using this on my blog in Ember CLI.

Do you want to convert this into an ember cli plugin?

**Comment by Glavin001** [comment]
I'm not very familiar with the Ember CLI structure. If you'd like to submit a pull request that would be great!

**Comment by Robdel12** [comment]
Awesome! Working on it :)

I have a question though. How did you go about creating a component without a view template?

**Comment by Glavin001** [comment]
>  How did you go about creating a component without a view template?

I used the `tagName` ( https://github.com/Glavin001/ember-c3/blob/master/lib/components/chart.js#L9 ) and then the `bindTo` option ( https://github.com/Glavin001/ember-c3/blob/master/lib/components/chart.js#L135 ). So the Ember Component would automatically create an element with tag `tagName` and it could be accessed with `this.get('element')` and then I passed that `element` via `bindTo` to C3 and it used that element to generate the chart. Hope that helps!

**Comment by Robdel12** [comment]
Gotcha. I have everything working now, most of my time has been spent messing around trying to get the example page to work.

**Comment by Glavin001** [comment]
Published ember-c3 v0.1.0 to npm
