### ISSUE TITLE
Model with relationships

### ISSUE THREAD

**Issue by egeriis** [Glavin001/ember-c3#19]
In the example application, a simple JSON object is used as the model: https://github.com/Glavin001/ember-c3/blob/master/app/scripts/routes/index_route.js

But is it possible to use a real Ember model? And can this model then supply columns through a relationship?

**Comment by Glavin001** [comment]
I think the main problem would be asynchronous nature of Ember models and relationships.

Could you provide some examples I could work with?

**Comment by maxwondercorn** [comment]
Please take a look at the `chart events` example in the new addon version. The controller uses computed properties to change the data into a format that c3 can use
