### ISSUE TITLE
Diff previous data with new data for detecting unloading of columns

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/ember-c3#34]

**Comment by bfcoder** [comment]
I ran into this problem.

I dealt with this by changing line 205
```
chart.load(data);
```

to this

```
var x;
data.columns.forEach(function(column) {
  if (column && column[0] === data.x) {
    x = column;
  }
});
if (!x || x.length <= 1) {
  chart.unload();
} else {
  chart.load(data);
}
````

The however does require you pass in a column designated as the x. And if you are passing in many columns and have not defined what the x will be, this would fall apart. In my case I have several columns and one of them is designated as an x. If you don't supply an x column, then a diff on each column might be the best way to go about it.

**Comment by Glavin001** [comment]
Thanks for sharing! I definitely want to support automatically unloading removed columns. When I am back working on this project, I will take a look at your approach and see if we can come up with something that works for everyone.

**Comment by maxwondercorn** [comment]
with release 1.0.0 you can use the c3.load() and unload() methods through the exposed chart object see the demo project and dummy app.  reference pr #88
