### ISSUE TITLE
Tag new version v0.1.6

### ISSUE THREAD

**Issue by AO16** [Glavin001/ember-c3#41]
Would you mind updating the tag on this project? 

We need the action hooks in our project. It would be greatly appreciated. 

Thanks for the work, this is a great addon.

**Comment by Glavin001** [comment]
I'll do that now. Thanks for reminder and your patience.

**Comment by AO16** [comment]
:+1: Thanks a bunch!

**Comment by Glavin001** [comment]
So I think using the GitHub [releases](https://github.com/Glavin001/ember-c3/releases) tags has been deprecated in favour of distributing over `npm`. I just published the latest to npm.
