### ISSUE TITLE
very slow rendering

### ISSUE THREAD

**Issue by ptmoy2** [Glavin001/ember-c3#42]
I'm using this addon to draw a timeseries chart consisting of 4 graphs (360 points each).  The 360 y-values of each of the 4 graphs are computed based on other user input properties.   The 4 graphs  are independent of each other (e.g., a certain input-property change may cause only y-values of one of the graphs to change).  In ember, I created 5 computed properties, one for the y-values of each graph, and the fifth computed property (named 'plotData') that depends on the other 4.  The last computed property builds the entire 'data' structure needed by C3.  I use the addon like this:  {{c3-chart data='plotData'}}.

Because I'm changing 'plotData' every time one of the 4 computed properties change, I think C3 is re-rendering the entire chart every time, which may be causing the slowness.  Is there anyway to get C3 to re-render only the graph that's changed?

**Comment by Glavin001** [comment]
I think #34 might help with improving speed by only unloading and [loading](https://github.com/Glavin001/ember-c3/blob/master/addon/components/c3-chart.js#L205) the changes.

#37 may also be useful for having raw access to the chart.

Unfortunately, both of which are not yet implemented.

---

However, I think that maybe C3 itself may be the problem. Looking at http://c3js.org/samples/data_load.html it is expected to use `chart.load` that to update values with the same column name. This is what Ember-C3 does: https://github.com/Glavin001/ember-c3/blob/master/addon/components/c3-chart.js#L205

Maybe write a basic example in only C3 and test the performance of that. If you can narrow down the problem to Ember-C3 let me know!

**Comment by maxwondercorn** [comment]
This is a very old issue but there are changes coming to ember-c3 as outlined in issue #77.  If you are still using the addon this issue may have been eliminated.

**Comment by maxwondercorn** [comment]
A 1.0.0 is being released, please open a new issue if not fixed with updates.  pr #88
