### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getItem' of undefined

### ISSUE THREAD

**Issue by danielspaniel** [Glavin001/ember-c3#49]
Hi there,
  We are happily using c3 for our charting fun times, but every time we click on a bar chart we get that error. Unfortunately the c3 js is minified so we can't see why. 
  This happens in our charts ( bar and line )  and also in your demo charts ( bar and line ) as well, but you don't do anything on click ( just hover ) .. whereas we are trying to do something on click .. but this error is spoiling our fun at the moment. 
  Any ideas? Suggestions.

**Comment by Glavin001** [comment]
You could change this file in Ember-C3: https://github.com/Glavin001/ember-c3/blob/master/index.js#L9-L11
Such that it does not use the minified version and instead uses the raw source code for C3 library. Then you could debug C3 on your own.
I hope that helps!

**Comment by danielspaniel** [comment]
duh .. should have thought of that .. thanks.
