### ISSUE TITLE
Data binding for params other than `data`

### ISSUE THREAD

**Issue by benoror** [Glavin001/ember-c3#51]
Hi @Glavin001, kudos for such a great addon :smile: 

I have a use case where I need data binding for the donut chart **title**:

<img width="295" alt="screen shot 2016-04-05 at 11 48 14" src="https://cloud.githubusercontent.com/assets/119117/14290364/651dd636-fb24-11e5-8a68-b9f771f782a2.png">

 similarly to the Gauge's example:

<img width="298" alt="screen shot 2016-04-05 at 11 49 21" src="https://cloud.githubusercontent.com/assets/119117/14290374/78f69abc-fb24-11e5-8f50-c26556ae254b.png">

I infer that data binding is not triggered because only the `data` parameter is observed: https://github.com/Glavin001/ember-c3/blob/master/addon/components/c3-chart.js#L193, while Gauge's title is extracted from `data` parameter itself, Donut's title is not (`donut` param)

I'm somewhat new to Ember, maybe you can hint me if there's a workaround for this, or maybe I'd be happy to work on a PR for it.

Thanks in advance, cheers!

**Comment by Glavin001** [comment]
As you noted, currently only changes to `data` update the chart.
This functionality could be improved.

When the component is initialized it creates a `chart` and passes the configuration from `_config` property to `generate` it: https://github.com/Glavin001/ember-c3/blob/master/addon/components/c3-chart.js#L118-L119

I am unfamiliar with a C3 API method that would allow you to load a changed `donut` or other parameters, only `chart.load(data)` for the changed `data`. 
I recommend you first contact C3 maintainer(s) and figure out how C3 would like you do this: https://github.com/masayuki0812/c3
Afterwards, let me know and we can discuss further how you will change Ember-C3 to allow other parameters to be updated by bindings.
Thanks!

**Comment by jsvg** [comment]
I'm working on a PR that should allow for this. Problem with updating pies/donuts is that data loaded into the chart object is appended. However, you should be able to specify whether you'd like the current data to be [unloaded](http://c3js.org/reference.html#api-unload) before the new data is loaded in.

**Comment by janyk** [comment]
@jsvg any luck with that PR regarding this issue?

**Comment by AO16** [comment]
I believe this is covered in #51

**Comment by AO16** [comment]
Sorry, #52

**Comment by maxwondercorn** [comment]
If you only have one donut chart, you can access the title via its class.

```
document.getElementsByClassName("c3-chart-arcs-title")[0].innerHTML = "my new title"
```

The c3 developers suggest using the classes for some uses or even falling back to d3 functions in some applications.  Sorry I don't have any links to reference.  Can't seem to find what I have read in the past.

**Comment by maxwondercorn** [comment]
Please see the drill down demo in release 1.0.0.  ref pr #88

**Comment by maxwondercorn** [comment]
Really old issue but wanted to show this is now possible by setting the title in the donut argument.

See donut example in the dummy app:
 
https://github.com/Glavin001/ember-c3/blob/f9dcce109e0efdbfd56d81b06233af12fc9d00b5/tests/dummy/app/controllers/donut.js#L16
