### ISSUE TITLE
Publish new release

### ISSUE THREAD

**Issue by AO16** [Glavin001/ember-c3#58]
Would you mind publishing a new release on bower, would be nice to have the `willDestroyElement` hook setup. Thanks for the addon!

**Comment by AO16** [comment]
We should put #59 in the release first though as it is currently broken.

**Comment by Glavin001** [comment]
Looking into this right now. 😃

**Comment by Glavin001** [comment]
Published npm release v0.3.0: https://www.npmjs.com/package/ember-c3

**Comment by Glavin001** [comment]
And I've added a GitHub release v0.3.0 so Bower should also work: https://github.com/Glavin001/ember-c3/releases/tag/v0.3.0

**Comment by AO16** [comment]
Thank you for taking the time to get this stuff merged in! If you need any help with this project now that you are off of ember, just let me know. I'd be happy to help you out when I have some time. Thanks again.

**Comment by Glavin001** [comment]
I've added you as a collaborator 😃 . Thank you for contributing and your support!
