### ISSUE TITLE
Docs are not working.  The domain blog.glavin.org is not working.

### ISSUE THREAD

**Issue by neaket360pi** [Glavin001/ember-c3#66]
When visiting http://blog.glavin.org/ember-c3/ I get a parked domain page by [zoneedit.com](https://support.zoneedit.com/index.php?/Knowledgebase/Article/View/33/4/why-am-i-seeing-a-parked-landing-page-on-a-zoneedit-domain)

It would be great to get the docs working again.  Maybe  http://glavin001.github.io/ember-c3/ could be updated to not redirect to blog.glavin.org.

**Comment by Glavin001** [comment]
It is working for me: 

![image](https://cloud.githubusercontent.com/assets/1885333/21704108/3e78a514-d38d-11e6-8492-bcddfa3c9915.png)

I would also like GitHub to stop redirecting to blog.glavin.org for these projects such as ember-c3, however it appears by setting up the CNAME for my blog on GitHub it automatically routes all of my other projects, too: https://github.com/Glavin001/Glavin001.github.io/blob/gh-pages/CNAME
This is unfortunate. If anyone knows how to get around it, please let me know! I do want my blog still to work, just exclude ember-c3.

**Comment by neaket360pi** [comment]
Thanks for checking.   I had the docs working for me as well.  However after a few refreshes I see the zoneedit page again.  

![image](https://cloud.githubusercontent.com/assets/4418194/21735155/9ea8dc12-d435-11e6-9a30-c9682d7c79ee.png)

I am not sure how you can have different CNAMES for your blog and other sites.  I think you could rename the project `Glavin001.github.io` to `blog` and use `glavin.org/blog`.  But then you would be breaking a lot of your links to `blog.glavin.org`

**Comment by JustInToCoding** [comment]
Same here, only seeing the zoneedit page

**Comment by allthesignals** [comment]
Anyone able to get the docs to work? I can help, just not sure what the issue is.

**Comment by Glavin001** [comment]
Investigating the DNS issues now. Thank you all for your patience.

**Comment by Glavin001** [comment]
Please try again. It looks to be fixed and working now.
