### ISSUE TITLE
Let consumers determine d3/c3 version

### ISSUE THREAD

**Issue by caseywatts** [Glavin001/ember-c3#72]
Consumers could include the node_module c3/d3 import directly, like this:
https://gist.github.com/caseywatts/347e18e4905c447859fa777ec97c34f8

**Comment by maxwondercorn** [comment]
See issue #77

**Comment by maxwondercorn** [comment]
pr #79 upgraded to the latest c3 and d3 versions.  Going forward we can upgrade as appropriate.  Updated addon wil published when issue #77 checklist is complete
