### ISSUE TITLE
BroccoliMergeTrees: Expected Broccoli node, got undefined for inputNodes[0]

### ISSUE THREAD

**Issue by w3o-io** [Glavin001/ember-c3#90]
Hi there,

This error appear - BroccoliMergeTrees: Expected Broccoli node, got undefined for inputNodes[0] after I update the ember-c3 version from 0.3.1 to 1.2.0 and ember build, my ember-cli version is 3.5.0.
Any ideas?

Thank you.

**Comment by maxwondercorn** [comment]
The error is caused when trying to merge c3.css with an empty vendors directory.  I'm surprised you're the first one to see this issue.  There are a couple ways of fixing this.  I'll get to the fix later today,

**Comment by maxwondercorn** [comment]
Issue should be resolved with release 1.2.1.  Thanks.
