### ISSUE TITLE
How can I make use of d3 functions when loading ember-c3?

### ISSUE THREAD

**Issue by scooterlord** [Glavin001/ember-c3#95]
Hello and thank you for this plugin.

I am trying to make use of d3.js functionality inside a controller but can't do it and don't want to install ember-d3 to avoid duplications. WIth a previous version of ember-c3 (0.3.1) I could normally use d3 functions inside a controller but now I can't.

Any ideas how to do this?

**Comment by maxwondercorn** [comment]
I'm not sure how you were using d3 previously.  The previous version was installing ember-d3 and also importing d3, so you could using directly or via ember-d3 imports.

The current version is using ember-auto-import for c3.  I can't test at the moment but I believe C3 is exposed if you re-import it into your app.  

```js
// in your app
import c3 from "c3";

// use c3...
```

If that's the case, I should be able to import D3 in the addon and then you could import it to use directly.

**Comment by scooterlord** [comment]
Thanks for the reply, however, I am talking about importing and using d3 functions and NOT c3 functions.

**Comment by maxwondercorn** [comment]
Sorry if I wasn’t clear. 

Since c3 is available to the application,  if I import d3 the same as c3, d3 would also be available to the application.

 I think I can test this sometime today

**Comment by maxwondercorn** [comment]
I tested the d3 import today and it works.  You will be able to `import d3 from "d3"` and then use d3 in your application

I'm updating the dummy application and readme. I should be able to push out a release sometime Friday

**Comment by scooterlord** [comment]
A million thanks :)
